### ISSUE TITLE
I ran the dots.sh so then?

### ISSUE THREAD

**Issue by DouglasMartinEX** [Axenide/Dotfiles#1]
Hey! Which "sh." i must run to install the dotfiles? Other dots generally comes with one install.sh or something but i dont see any here. What the next step after dots.sh?

I a newbie btw, newer installing hyprdots so i apretieted if you show me how to install your beutiful dotfiles! Tnx!

**Comment by Axenide** [comment]
Hello! The installation process is in the README.md of this repo. Indeed, you have to run `dots.sh` to install the Dotfiles, but this doesn't install the required packages to which the config belongs to.

Check inside dots/.config to see which packages you need. I'll add them to the script later so people can have my setup without them having to install the packages by themselves. :)

I don't know how much of a newbie you are, you need the packages for the config to work heh.
