### ISSUE TITLE
Required packages

### ISSUE THREAD

**Issue by 6R1MR34P3R** [Axenide/Dotfiles#3]
Hi and sorry if adressed somewhere. New to Hyprland here. Could you say wich ones are the required packages for this?

**Comment by Axenide** [comment]
Hi! Don't worry, I didn't add the required packages yet.
If I remember correctly, you need:
`hyprland nemo swayosd swaync swaylock-effects-git waybar rofi-lbonn-wayland kitty fish`
Those are the required packages to have a functional experience. The rest of the packages in the config are:
`btop cava neofetch ranger tmux webcord zathura rofimoji rofi-calc grim slurp playerctl`
Maybe I'm forgetting something. Tomorrow I will check and update the script with an automatic installation for these.
