### ISSUE TITLE
Could you provide the wallpapers

### ISSUE THREAD

**Issue by FormalSnake** [Axenide/Dotfiles#6]
I want to use some of these configs on macOS, but the wallpaper app thing doesn't work on macOS I assume.

**Comment by Axenide** [comment]
It won't work on macOS since everything was designed for Hyprland, however you can get the Wallpapers [here](https://github.com/Axenide/Wallpapers).

**Comment by FormalSnake** [comment]
I am trying to port some stuff, I know it wouldn't work by copying the configs on mac.
Thanks for the wallpapers.
