### ISSUE TITLE
dots.sh is not working

### ISSUE THREAD

**Issue by cr4sh-me** [Axenide/Dotfiles#7]
Is dots.sh supposed to copy all config and setup everything?
Its just installing some packages

**Comment by Axenide** [comment]
Do you have stow installed? It creates symlinks to the config files so you have a `Dotfiles` folder in your home that you can use in a repository, just like me with this setup. :)

But stow is supposed to be installed with the script, so this is weird, unless you cloned the repo before I fixed that.

**Comment by cr4sh-me** [comment]
Well, I already copied config files manually, but  stow was installed before I ran dots.sh script

**Comment by Axenide** [comment]
That's really weird, it worked on all my machines and no one else has had this problem.

If you have any idea of what happened, please feel free to re-open the issue. :)
