### ISSUE TITLE
13 errors

### ISSUE THREAD

**Issue by Stove-git** [Axenide/Dotfiles#8]
idk how to make it show all of the errors

**Comment by Stove-git** [comment]
alright fixed some of them by removing the deprecated fakefullscreen toggle now it cant find the colors which i cant set

**Comment by Stove-git** [comment]
@Axenide ```steve@Sigmie ~> hyprctl configerrors
Config error in file /home/steve/.config/hypr/source/binds.conf at line 81: Invalid dispatcher, requested "fakefullscreen" does not exist
Config error in file /home/steve/.config/hypr/hyprland.conf at line 19: Config error in file /home/steve/.config/hypr/source/binds.conf at line 81: Invalid dispatcher, requested "fakefullscreen" does not exist
Config error in file /home/steve/.config/hypr/hyprland.conf at line 23: source= globbing error: found no match
Config error in file /home/steve/.config/hypr/source/appearance.conf at line 1: source= globbing error: found no match
Config error in file /home/steve/.config/hypr/hyprland.conf at line 24: Config error in file /home/steve/.config/hypr/source/binds.conf at line 81: Invalid dispatcher, requested "fakefullscreen" does not exist
Config error in file /home/steve/.config/hypr/hyprland.conf at line 19: Config error in file /home/steve/.config/hypr/source/binds.conf at line 81: Invalid dispatcher, requested "fakefullscreen" does not exist
Config error in file /home/steve/.config/hypr/hyprland.conf at line 23: source= globbing error: found no match
Config error in file /home/steve/.config/hypr/source/appearance.conf at line 1: source= globbing error: found no match
Config error in file /home/steve/.config/hypr/source/misc.conf at line 6: config option <misc:no_direct_scanout> does not exist.
Config error in file /home/steve/.config/hypr/hyprland.conf at line 25: Config error in file /home/steve/.config/hypr/source/binds.conf at line 81: Invalid dispatcher, requested "fakefullscreen" does not exist
Config error in file /home/steve/.config/hypr/hyprland.conf at line 19: Config error in file /home/steve/.config/hypr/source/binds.conf at line 81: Invalid dispatcher, requested "fakefullscreen" does not exist
Config error in file /home/steve/.config/hypr/hyprland.conf at line 23: source= globbing error: found no match
Config error in file /home/steve/.config/hypr/source/appearance.conf at line 1: source= globbing error: found no match
Config error in file /home/steve/.config/hypr/hyprland.conf at line 24: Config error in file /home/steve/.config/hypr/source/binds.conf at line 81: Invalid dispatcher, requested "fakefullscreen" does not exist
Config error in file /home/steve/.config/hypr/hyprland.conf at line 19: Config error in file /home/steve/.config/hypr/source/binds.conf at line 81: Invalid dispatcher, requested "fakefullscreen" does not exist
Config error in file /home/steve/.config/hypr/hyprland.conf at line 23: source= globbing error: found no match
Config error in file /home/steve/.config/hypr/source/appearance.conf at line 1: source= globbing error: found no match
Config error in file /home/steve/.config/hypr/source/misc.conf at line 6: config option <misc:no_direct_scanout> does not exist.```

**Comment by Axenide** [comment]
Try using the Python installer, the Shell one is outdated. It should generate the colors before setting all the configs.

**Comment by Stove-git** [comment]
> Try using the Python installer, the Shell one is outdated. It should generate the colors before setting all the configs.

the errora didnt go away the theme is black white in terminal and rofi

**Comment by Stove-git** [comment]
> Try using the Python installer, the Shell one is outdated. It should generate the colors before setting all the configs.

also i dont have the colors.conf in my hypr/source

**Comment by Axenide** [comment]
I'll have to check this later, right now I'm not having those errors even on a fresh install.
Thank you for letting me know, I'll try my best to fix this.

**Comment by Stove-git** [comment]
alright

**Comment by Stove-git** [comment]
have u found something yet?

**Comment by Stove-git** [comment]
have u found something yet?

**Comment by Stove-git** [comment]
have u found something yet?

**Comment by Axenide** [comment]
I'll let you know when I do, I'm at university so I don't have a lot of time to mantain this repo.

**Comment by Axenide** [comment]
I forgot about this, you may try now. The problem was some config updates from Hyprland. :)
